# helm/app/values.yaml  (Basis-Defaults)

frontend:
  enabled: true
  image: ""                 # wird pro Release gesetzt (v1/v2)
  replicas: 1
  containerPort: 8501
  servicePort: 80
  env: []                   # optional ENV-Variablen
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []      # z.B. [{ name: regcred }] falls GHCR privat

backend:
  enabled: false            # Backend komplett aus
  image: ""
  replicas: 0

database:
  enabled: false            # DB komplett aus
  image: ""
  replicas: 0

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: ""              # pfadbasiert
      paths:
        - path: /           # wird pro Release überschrieben (v1/v2)
          pathType: Prefix
