apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-hello
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: demo-hello
  namespaceSelector:
    matchNames: ["demo"]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
