apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - port: {{ .Values.database.servicePort }}
      targetPort: {{ .Values.database.containerPort }}
      protocol: TCP