apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: {{ .Values.database.image }}
          ports:
            - containerPort: {{ .Values.database.containerPort }}
          env:
            {{- range .Values.database.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}