apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-frontend
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.servicePort | default 80 }}
      targetPort: {{ .Values.frontend.containerPort | default 8501 }}
      protocol: TCP
