{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  selector:
    app: grafana
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
      nodePort: {{ .Values.grafana.service.nodePort | default "" }}
{{- end }}